apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: builds.build.pivotal.io
spec:
  group: build.pivotal.io
  version: v1alpha1
  names:
    kind: Build
    singular: build
    plural: builds
    shortNames:
    - cnbbuild
    - cnbbuilds
    - bld
  scope: Namespaced
  subresources:
    status: {}
  additionalPrinterColumns:
  - name: SHA
    type: string
    JSONPath: ".status.SHA"