#@ load("@ytt:data", "data")

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpack-controller
  namespace: kpack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kpack-controller
  template:
    metadata:
      labels:
        app: kpack-controller
        version: #@ data.values.version
    spec:
      serviceAccountName: controller
      containers:
      - name: controller
        image: #@ data.values.controller.image
        env:
        - name: BUILD_INIT_IMAGE
          value: #@ data.values.build_init.image
        - name: REBASE_IMAGE
          value: #@ data.values.rebase.image
        - name: COMPLETION_IMAGE
          value: #@ data.values.completion.image
        - name: LIFECYCLE_IMAGE
          value: #@ data.values.lifecycle.image
