apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: custombuilders.experimental.kpack.pivotal.io
spec:
  group: experimental.kpack.pivotal.io
  version: v1alpha1
  names:
    kind: CustomBuilder
    singular: custombuilder
    plural: custombuilders
    shortNames:
    - custmbldr
    categories:
    - kpack
  scope: Namespaced
  subresources:
    status: {}