#@ load("@ytt:data", "data")
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: resource.webhook.kpack.pivotal.io
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: kpack-webhook
      namespace: kpack
  failurePolicy: Fail
  name: resource.webhook.kpack.pivotal.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpack-webhook
  namespace: kpack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kpack-webhook
  template:
    metadata:
      labels:
        app: kpack-webhook
        role: webhook
        version: dev
    spec:
      serviceAccountName: webhook
      containers:
      - name: webhook
        image: webhook_image
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Sources
sources:
- image: webhook_image
  path: ./
  pack:
    build:
      builder: cloudfoundry/cnb:bionic
      rawOptions:
      - "-e BP_GO_TARGETS=./cmd/wehbook"
---
apiVersion: kbld.k14s.io/v1alpha1
kind: ImageDestinations
destinations:
- image: webhook_image
  newImage: gcr.io/cf-build-service-public/testing/webhook
